## date format used, either "us" or "uk"
dialect = "uk"

## default timezone
timezone = "local"

## enable or disable automatic sync
auto_sync = false

## enable or disable automatic update checks
update_check = true

## address of the sync server
# sync_address = "https://atuin-homelab.lucatrifilio.it"

## how often to sync history
# sync_frequency = "10m"

## which search mode to use
## possible values: prefix, fulltext, fuzzy, skim
search_mode = "fulltext"

## which filter mode to use by default
## possible values: "global", "host", "session", "session-preload", "directory", "workspace"
filter_mode = "host"

## which style to use
## possible values: auto, full, compact
style = "auto"

invert = false
show_preview = true
show_numeric_shortcuts = false
enter_accept = true

# secrets_filter = true
# prefers_reduced_motion = false

[stats]
# common_subcommands = ["apt", "cargo", "docker", "git", "go", "kubectl", "npm", "systemctl", "tmux"]
# common_prefix = ["sudo"]
# ignored_commands = ["cd", "ls", "vi"]

[keys]
# scroll_exits = true

[sync]
records = true

[preview]
# strategy = "auto"

[daemon]
# enabled = false
# autostart = false

[theme]
name = "catppuccin-macchiato-sky"

[search]
# filters = [ "global", "host", "session", "session-preload", "workspace", "directory" ]

[tmux]
enabled = true

[ui]
# columns = ["duration", "time", "command"]
