#!/bin/bash
# Catppuccin Macchiato palette
export BASE=0xFF24273A
export MANTLE=0xFF1E2030
export SURFACE0=0xFF363A4F
export SURFACE1=0xFF494D64
export OVERLAY1=0xFF8087A2
export TEXT=0xFFCAD3F5
export SUBTEXT0=0xFFA5ADCB
export MAUVE=0xFFC6A0F6
export RED=0xFFED8796
export PEACH=0xFFF5A97F
export YELLOW=0xFFEED49F
export GREEN=0xFFA6DA95
export TEAL=0xFF8BD5CA
export BLUE=0xFF8AADF4
export SAPPHIRE=0xFF7DC4E4
export LAVENDER=0xFFB7BDF8
export TRANSPARENT=0x00000000

# Bar
export BAR_COLOR=0xA624273A
export BAR_BORDER_COLOR=$SURFACE0

# Fonts
export FONT="JetBrainsMono Nerd Font"
export FONT_FACE="JetBrainsMono Nerd Font"
export ICON_FONT="sketchybar-app-font:Regular:14.0"
export FONT_SIZE=13

# Geometry
export BAR_HEIGHT=32
export BAR_MARGIN=8
export BAR_Y_OFFSET=4
export BAR_CORNER_RADIUS=9
export ITEM_PADDING=4
export ICON_PADDING=6
export LABEL_PADDING=6

# Item defaults
export ITEM_BG_COLOR=$SURFACE0
export ITEM_BORDER_COLOR=$SURFACE1
export ITEM_HEIGHT=24
export ITEM_CORNER_RADIUS=7

# Workspace pills
export WORKSPACE_ITEM_COLOR=$SURFACE0
export WORKSPACE_ITEM_ACTIVE_COLOR=$PEACH
export WORKSPACE_ITEM_BORDER_COLOR=$SURFACE1
export WORKSPACE_ITEM_BORDER_HIGHLIGHT_COLOR=$PEACH
export WORKSPACE_ICON_COLOR=$SUBTEXT0
export WORKSPACE_ICON_HIGHLIGHT_COLOR=$TEXT
export WORKSPACE_LABEL_COLOR=$SUBTEXT0
export WORKSPACE_LABEL_HIGHLIGHT_COLOR=$TEXT

# Clock
export CLOCK_ICON_COLOR=$BLUE
export CLOCK_LABEL_COLOR=$TEXT

# Battery
export BATTERY_ICON_COLOR_GREEN=$GREEN
export BATTERY_ICON_COLOR_YELLOW=$YELLOW
export BATTERY_ICON_COLOR_RED=$RED
export BATTERY_LABEL_COLOR=$TEXT

# Volume
export VOLUME_ICON_COLOR=$TEXT
export VOLUME_LABEL_COLOR=$TEXT
export VOLUME_ICON_COLOR_GREEN=$GREEN
export VOLUME_ICON_COLOR_YELLOW=$YELLOW
export VOLUME_ICON_COLOR_ORANGE=$PEACH
export VOLUME_ICON_COLOR_RED=$RED
export VOLUME_SLIDER_HIGHLIGHT_COLOR=$PEACH
export VOLUME_SLIDER_BG_COLOR=$SURFACE1
export VOLUME_OUTPUT_POPUP_LABEL_COLOR=$SUBTEXT0
export VOLUME_OUTPUT_POPUP_SELECTED_LABEL_COLOR=$BLUE

# IP
export IP_ICON_COLOR_VPN=$TEAL
export IP_ICON_COLOR_WIFI=$BLUE
export IP_ICON_COLOR_OFFLINE=$RED
export IP_LABEL_COLOR=$TEXT

# Media
export MEDIA_ICON_COLOR=$SUBTEXT0
export MEDIA_ICON_PLAYING_COLOR=$RED
export MEDIA_LABEL_COLOR=$TEXT
